---

version: '3.7'
services:

  chtmll:
    build:
      dockerfile: docker/Dockerfile
      context: ../
    command:
      - /bin/sh
      - -c
      - |
        bundle exec rake db:migrate RAILS_ENV=test
        bundle exec rspec -f p
    environment:
      RAILS_ENV: test
      DB_HOST: postgres
      DB_NAME: chtmll
      DB_USERNAME: chtmll
      DB_PASSWORD: chtmll
    links:
      - postgres
    networks:
      - default

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: chtmll
      POSTGRES_USER: chtmll
      POSTGRES_PASSWORD: chtmll
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - default

volumes:
  postgres_data:


networks:
  default:
    external: false
