default: &default
  adapter: <%= ENV.fetch('DB_ADAPTER') { 'postgresql' } %>
  encoding: <%= ENV.fetch('DB_ENCODING') { 'unicode' } %>
  pool: <%= ENV.fetch('DB_POOL') { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
